export const helpText: Record<string, string> = {
  pwd: 'pwd - print name of current/working directory',
  ls: 'ls [-la] [path] - list directory contents\n  -l  long format\n  -a  show hidden files',
  cd: 'cd [directory] - change the working directory\n  With no args, changes to $HOME',
  cat: 'cat [file] - concatenate and display file contents',
  touch: 'touch [file] - create an empty file or update timestamp',
  mkdir: 'mkdir [directory] - create a directory',
  rm: 'rm [-r] [file] - remove files or directories\n  -r  remove directories recursively',
  cp: 'cp [source] [dest] - copy a file',
  mv: 'mv [source] [dest] - move or rename a file',
  chmod: 'chmod [mode] [file] - change file permissions',
  grep: 'grep [-i] [pattern] [file] - search for pattern in file\n  -i  case-insensitive\n  Reads from stdin if no file given',
  find: 'find [path] [-name pattern] [-type f|d] - search for files',
  head: 'head [-n count] [file] - display first lines of a file\n  Default: 10 lines',
  tail: 'tail [-n count] [file] - display last lines of a file\n  Default: 10 lines',
  wc: 'wc [-lwc] [file] - count lines, words, characters\n  -l  lines only\n  -w  words only\n  -c  characters only',
  echo: 'echo [text...] - display text',
  sort: 'sort [-r] [file] - sort lines of text\n  -r  reverse order',
  uniq: 'uniq [-c] [file] - remove adjacent duplicate lines\n  -c  prefix lines with occurrence count',
  export: 'export [NAME=value] - set environment variable\n  With no args, lists all variables',
  env: 'env - display all environment variables',
  clear: 'clear - clear the terminal screen',
  history: 'history - display command history',
  man: 'man [command] - display manual page for a command',
};
