export const DEFAULT_LINE_COUNT = 10;
export const HINT_DISPLAY_MS = 5000;
export const HOME_DIRECTORY = '/home/user';
export const MAX_REGEX_LENGTH = 100;

export const ACHIEVEMENT_THRESHOLDS = {
  FIRST_STEPS: 1,
  APPRENTICE: 5,
  JOURNEYMAN: 10,
  EXPLORER_COMMANDS: 100,
  POWER_USER_COMMANDS: 500,
  XP_HUNTER: 1000,
  XP_LEGEND: 5000,
} as const;
